<?php defined("BASEPATH") OR exit("No direct script access allowed");$active_group = "default";
          $query_builder = TRUE;
$db["default"] = array("dsn"  => "",
"hostname" => "us-cdbr-iron-east-01.cleardb.net", 
"username" => "be522ec9513f95" ,
"password" => "80adca5d08feb47",
"database" => "heroku_928496075409a6a",
"dbdriver" => "mysqli",
"pconnect" => FALSE,
"db_debug" => (ENVIRONMENT !== "production"),
"cache_on" => FALSE,
"cachedir" => "",
"char_set" => "utf8",
"dbcollat" => "utf8_general_ci",
"swap_pre" => "",
"encrypt" => FALSE,
"compress" => FALSE,
"stricton" => FALSE,
"failover" => array(),
"save_queries" => TRUE);
